# Generated by Django 2.2.3 on 2019-07-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
        ('travel_buddy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bookings',
            field=models.ManyToManyField(related_name='bookings', to='login_reg_app.User'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
